### ISSUE TITLE
google-talk-bot example failed to login to talk.google.com

### ISSUE THREAD

**Issue by duyanh030** [RestComm/jain-slee.xmpp#2]
I got failure from google talk when trying to login using "slee.gtalk.bot" account.
2017-04-25 15:00:19,638 ERROR 

> [javax.slee.SbbNotification[service=ServiceID[name=GoogleTalkBotService,vendor=restcomm,version=0.1],sbb=SbbID[name=GoogleTalkBotSbb,vendor=restcomm,version=0.1]].GoogleTalkBotSbbImpl] (SLEE-EventRouterExecutor-4-thread-1) Connection to server failed!: 
>   -- caused by: SASL authentication failed: 
> 	at org.restcomm.slee.resource.xmpp.XmppResourceAdaptorSbbInterfaceImpl.connectClient(XmppResourceAdaptorSbbInterfaceImpl.java:78)
> 	at org.restcomm.examples.googletalk.GoogleTalkBotSbb.onStartServiceEvent(GoogleTalkBotSbb.java:59)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.mobicents.slee.runtime.sbbentity.SbbEntityImpl.invokeEventHandler(SbbEntityImpl.java:395)
> 	at org.mobicents.slee.runtime.eventrouter.routingtask.EventRoutingTaskImpl.routeQueuedEvent(EventRoutingTaskImpl.java:293)
> 	at org.mobicents.slee.runtime.eventrouter.routingtask.EventRoutingTaskImpl.run(EventRoutingTaskImpl.java:88)
> 	at org.mobicents.slee.runtime.eventrouter.EventRouterExecutorImpl$EventRoutingTaskStatsCollector.run(EventRouterExecutorImpl.java:43)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)

**XMPP protocol returned by google talk**

**

> `<failure xmlns="urn:ietf:params:xml:ns:xmpp-sasl">`

**

I did test with my personal google talk account. Every thing looks fine. 
May be having problem with account "slee.gtalk.bot" configuration or password is changed.

**Comment by duyanh030** [comment]
Please try to enable permision 'less secure apps' to fix the problem

https://github.com/node-xmpp/client/issues/75

**Comment by satanatoly** [comment]
fixed as suggested @duyanh030  by enabling "less secure apps" for test google test account

**Comment by FarhanAhmad** [comment]
I am facing the same problem and this link is not working: https://github.com/node-xmpp/client/issues/75
How and where to enable "less secure apps" permission?
